name: sing-box

networks:
  localnet:
    external: true

services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    restart: always
    networks:
      localnet:
        ipv4_address: 172.20.0.10
    ports:
      - 443:443
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
      - type: bind
        source: ./config.json
        target: /etc/sing-box/config.json

    command: -D /var/lib/sing-box -C /etc/sing-box/ run

    logging:
      driver: "local"
      options:
        max-size: "100m"
