storage:
  type: sqlite
  path: /data/data.db

security:
  basic:
    username: "USERNAME"
    password-bcrypt-base64: "PASSWORD"

ui:
  title: "Gatus"
  dashboard-heading: "Dashboard"
  dashboard-subheading: "Don't you dare go Hollow"

alerting:
  telegram:
    token: "TOKEN"
    id: "CHAT_ID"
    default-alert:
      enabled: true
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

  custom:
    url: "https://api.telegram.org/bot${TOKEN}/sendMessage"
    method: "POST"
    headers:
      Content-Type: "application/json"
    placeholders:
      ALERT_TRIGGERED_OR_RESOLVED:
        TRIGGERED: "🟥 *ACHTUNG*\n\n*State:*       `Down`"
        RESOLVED: "🟩 *WIEDERHERGESTELLT*\n\n*State:*       `Up`"
    body: |
      {
        "chat_id": "CHAT_ID",
        "parse_mode": "MarkdownV2",
        "text": "[ALERT_TRIGGERED_OR_RESOLVED]\n*Service:*    `[ENDPOINT_NAME]`\n*Target:*     `[ENDPOINT_URL]`"
      }
    default-alert:
      enabled: true
      send-on-resolved: true
      failure-threshold: 3
      success-threshold: 2

x-endpoints-common: &x-endpoints-common
  alerts:
    # - type: telegram
    - type: custom

x-endpoints-https: &x-endpoints-https
  interval: 30s
  conditions:
    - "[STATUS] == 200"
    - "[RESPONSE_TIME] < 5000"
    - "[CERTIFICATE_EXPIRATION] > 72h"

x-endpoints-domain: &x-endpoints-domain
  interval: 1h
  conditions:
    - "[DOMAIN_EXPIRATION] > 168h"

x-endpoints-ssh: &x-endpoints-ssh
  interval: 1m
  body: '{ "command": "/bin/true" }'
  conditions:
    - "[CONNECTED] == true"

endpoints:
  #
  # https monitors
  #
  - name: "HTTPS"
    <<: [*x-endpoints-common, *x-endpoints-https]
    url: "https://ENDPOINT"

  #
  # domain expiration monitors
  #
  - name: "DOMAIN"
    <<: [*x-endpoints-common, *x-endpoints-domain]
    url: "https://ENDPOINT"

  #
  # ssh monitors
  #
  # > .ssh/authorized_keys
  # restrict,command="/bin/true" SSH_PUB_KEY
  - name: "SSH"
    <<: [*x-endpoints-common, *x-endpoints-ssh]
    url: "ssh://ENDPOINT"
    ssh:
      username: "USERNAME"
      private-key: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        KEY
        -----END OPENSSH PRIVATE KEY-----
