name: filebrowser

networks:
  localnet:
    external: true

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always
    networks:
      localnet:
        ipv4_address: 172.20.0.30
    volumes:
      - type: bind
        source: ./data/files
        target: /srv
      - type: bind
        source: ./data/db
        target: /database
      - type: bind
        source: ./data/config
        target: /config
