name: vaultwarden

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      localnet:
        ipv4_address: 172.20.0.40
    environment:
      DOMAIN: https://DOMAIN/vault
      SIGNUPS_ALLOWED: false
      INVITATIONS_ALLOWED: false
      EXTENDED_LOGGING: true
      SHOW_PASSWORD_HINT: false
      LOG_LEVEL: warn
    volumes:
      - ./data/:/data/

    logging:
      driver: "local"
      options:
        max-size: "100m"

networks:
  localnet:
    external: true
