user                        nginx;
worker_processes            auto;

error_log                   /dev/stdout warn;
# error_log                   /etc/nginx/logs/error.log warn;
pid                         /var/run/nginx.pid;

events {
    worker_connections      1024;
}

http {
    default_type            application/octet-stream;

    log_format              main "[$time_local]\n\tclient:\t\t$proxy_protocol_addr:$proxy_protocol_port ($remote_addr:$remote_port)\n\tsni:\t\t$ssl_server_name\n\tuser:\t\t$remote_user\n\trequest:\t$request\n\treferer:\t$http_referer\n\tuser agent:\t$http_user_agent\n\tstatus:\t\t$status";
    access_log              /dev/stdout main;
    # access_log              /etc/nginx/logs/access.log main;

    sendfile                on;
    tcp_nopush              on;
    tcp_nodelay             on;

    keepalive_timeout       60;
    client_body_timeout     15;
    client_header_timeout   15;
    send_timeout            10;

    gzip                    on;
    gzip_types              text/plain text/css text/javascript application/json application/javascript application/wasm font/woff2;

    server_tokens           off;

    resolver                127.0.0.11 valid=300s;
    resolver_timeout        5s;

    # https only
    server {
        listen                  443 ssl default_server proxy_protocol;
        server_name             _;
        ssl_reject_handshake    on;
    }

    # https only
    server {
        listen              443 ssl proxy_protocol;
        http2               on;

        server_name         DOMAIN;
        server_tokens       off;

        # SSL
        ssl_protocols               TLSv1.3; # TLSv1.2 TLSv1.3;
        ssl_session_cache           shared:SSL:10m;
        ssl_session_tickets         off;
        ssl_session_timeout         30m;
        # ssl_ciphers                 ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
        # ssl_ecdh_curve              X25519:prime256v1:secp384r1;
        # ssl_prefer_server_ciphers   off;

        # certificates
        ssl_certificate             /etc/letsencrypt/live/DOMAIN/fullchain.pem;
        ssl_certificate_key         /etc/letsencrypt/live/DOMAIN/privkey.pem;
        ssl_trusted_certificate     /etc/letsencrypt/live/DOMAIN/chain.pem;

        root                        /data;

        # hug the robots
        location = /robots.txt {
            default_type        text/plain;
            return              200 "User-agent: *\nDisallow: /\n";
        }

        # default masquerade target for VLESS | Hysteria
        location / {
            default_type                            text/html;
            add_header Referrer-Policy              "same-origin" always;
            add_header Strict-Transport-Security    "max-age=31536000; includeSubDomains; preload" always;
            add_header X-Content-Type-Options       "nosniff" always;
            add_header X-Frame-Options              "sameorigin" always;

            index               index.html;
        }

        # proxy subscriptions
        # replace sub with
        # tr -dc 'A-Za-z0-9' </dev/urandom | head -c 64; echo
        location /sub/ {
            default_type                            text/plain;
            add_header Referrer-Policy              "same-origin" always;
            add_header Strict-Transport-Security    "max-age=31536000; includeSubDomains; preload" always;
            add_header X-Content-Type-Options       "nosniff" always;
            add_header X-Frame-Options              "sameorigin" always;

            location ~* \.yaml$ {
                try_files         $uri =403;
            }
            return                403;
        }
    }
}
