name: hysteria2

networks:
  localnet:
    external: true

services:
  hysteria2:
    image: tobyxdd/hysteria:latest
    container_name: hysteria2
    restart: always
    networks:
      localnet:
        ipv4_address: 172.20.0.15
    ports:
      - 443:443/udp
    volumes:
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt
        read_only: true
      - type: bind
        source: ./hysteria2.yml
        target: /etc/hysteria2.yml
    command: ["server", "-c", "/etc/hysteria2.yml"]
    environment:
      HYSTERIA_LOG_LEVEL: info
      HYSTERIA_LOG_FORMAT: console

    logging:
      driver: "local"
      options:
        max-size: "100m"
