name: xray

services:
  xray:
    image: ghcr.io/xtls/xray-core
    container_name: xray
    restart: always
    network_mode: host
    user: root
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./config/:/usr/local/etc/xray/
    command: run -c /usr/local/etc/xray/config.json

    logging:
      driver: "local"
      options:
        max-size: "100m"
