name: glance

networks:
  localnet:
    external: true

services:
  glance:
    image: glanceapp/glance:latest
    container_name: glance
    restart: always
    networks:
      localnet:
        ipv4_address: 172.20.0.30
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ./glance.yml
        target: /app/config/glance.yml

    logging:
      driver: "local"
      options:
        max-size: "100m"
