name: sslh

networks:
  localnet:
    external: true

services:
  sslh:
    image: ghcr.io/yrutschle/sslh:latest
    container_name: sslh
    restart: always
    networks:
      localnet:
        ipv4_address: 172.20.0.2
    ports:
      - 443:443
    volumes:
      - type: bind
        source: ./sslh.cfg
        target: /etc/sslh/sslh.cfg

    command: -F/etc/sslh/sslh.cfg

    logging:
      driver: "local"
      options:
        max-size: "100m"
